# Numpy

In [1]:
import numpy as np

In [4]:
np.__version__

'2.2.3'

### creating the empty array

In [6]:
np_array = np.array([])

In [7]:
np_array

array([], dtype=float64)

### creating array from list 

In [9]:
list1 = [1,2,3,4,5,6,7,8,9]
cvt_array = np.array(list1)
print(cvt_array,type(cvt_array))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


### creating array from tuples

In [11]:
tuple1 = (1,2,3,4,5,6,7,8,9,10)
tuple_to_array = np.array(tuple1)
print(tuple_to_array,type(tuple_to_array))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


## [1,2,3,4,5,6,7,8,9] this are one dimentional array 

### datatype

In [14]:
float1 = np.array([1.0,2.5,3.6,4.5,1.8,5.2])
data_type = float1.dtype
print(data_type)

float64


## string array 

In [16]:
str_array = np.array(['apple','banana','mango','orange','kiwi'])
print(str_array,str_array.dtype)

['apple' 'banana' 'mango' 'orange' 'kiwi'] <U6


## uppercasting

In [18]:
str_upper = np.array(['apple',100,2.565,True])
print(type(str_upper) ,str_upper) # here all data convert to the string beacause string are more flexiable 

<class 'numpy.ndarray'> ['apple' '100' '2.565' 'True']


Notice that in the code given above, numerical values have been converted into strings. This is because arrays can't have mixed types of data. Therefore, NumPy performs what is called upcasting, which is automatic promotion of data types to a higher-level type to ensure that all elements in an operation can be handled consistently. NumPy will upcast the data types to a common type that can accommodate both inputs without loss of information.



### array from set

In [21]:
set1 = {1.2,2.3,5.6,4.987,1.254,1.478}
array1 = np.array(set1)
print(array1,type(array1))

{1.2, 2.3, 1.254, 4.987, 5.6, 1.478} <class 'numpy.ndarray'>


In [22]:
print(array1[0])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

Notice even though we have created an array from a set, the resulting array retains the curly braces from the set. Further, when we tried to access an element from the resulting array, the interpreter threw the above error.


This is mainly because sets in Python are unordered collections of unique elements, whereas NumPy arrays are ordered collections. NumPy creates a zero-dimensional array which cannot be indexed. Hence creating arrays directly from sets is not a common practice, and it's not typically suggested.





## Understanding NumPy Arrays and Mixed Data Types


NumPy is designed to work with large amounts of numerical data efficiently. One of its key features is that all elements in a NumPy array must have the same data type (e.g., all integers, all floats, or all strings).

But what happens when we try to create a NumPy array from a list containing different data types?

In [44]:
mixedlist = [[1,2,3],'apple',10.245,-5,True]
ct_array = np.array(mixedlist)
print(ct_array)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

🔴 This gives an error because NumPy expects a consistent data type, but our list contains:

A list [2, 3, 1]
A string 'New York'
A float 5.6
An integer -10
Another string 'John'
These data types are too different for NumPy to convert into a single, uniform array.



so the solution is 

In [46]:
ct_array = np.array(object = mixedlist, dtype ='object')
print(ct_array, type(ct_array))

[list([1, 2, 3]) 'apple' 10.245 -5 True] <class 'numpy.ndarray'>


To force NumPy to accept different types, we can specify dtype='object'. This tells NumPy to treat every element as a general Python object:

# Multidimensional Arrays

## creating 2d array 

In [ ]:
list_2_dim = [1,2,3],[4,5,6]
array_2d  = np.array(list_2_dim)
print(array_2d)

## creating 3d array 

In [ ]:
list_3d =[ [[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
array_3d = np.array(list_3d)
print(array_3d)

Checking the number of dimensions in an array

In [48]:
tem = [
    [
        [20,24,25,26,29,24],
        [24,22,21,27,26,28],
        [22,25,24,25,26,27]
    ],
    [
        [25,26,23,24,24,25],
        [24,25,26,27,28,29],
        [29,21,20,24,26,23]
    ]
]
mk_array = np.array(tem)
mk_dim = np.ndim(mk_array)
print('the dimensional of this array is ',mk_dim)

the dimensional of this array is  3


### shape

In [50]:
# 1D array (Vector)
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)

# 2D array (Matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)

# 3D array (Tensor)
array_3d = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ],
    [
        [7, 8, 9], [10, 11, 12]
    ]
])
print("\n3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


simple way to make the array according to there dimensional

In [52]:
var = np.array([1,2,3],ndmin = 4)
dimen_array = np.ndim(var)
print(var)
print(var.shape)
print(dimen_array)

[[[[1 2 3]]]]
(1, 1, 1, 3)
4


### key difference of ndim and ndmin

Use ndim to check how many dimensions an array has.


Use ndmin to force an array to have at least a certain number of dimensions.

In [54]:
var = np.array([[2, 5, 3, 4], [1, 6, 4, 2], [7, 8, 4, 1]]) 
var_dim = np.ndim(var)
print(var)
print(var_dim)
print('the size func :',var.size)
print('the shape func :',var.shape)
print(var.shape[0])
print(var.shape[1])

[[2 5 3 4]
 [1 6 4 2]
 [7 8 4 1]]
2
the size func : 12
the shape func : (3, 4)
3
4


# Accessing NumPy Array Elements

### Accessing elements in 1-dimensional arrays

In [ ]:
new = np.array([1,2,3,4,5,6,7,8,9])
print(new[0:5])
print(new[0:9:2])#act same like the slicing 
print(new[::-1])
print(new[5:0:-1])
print(new[-1])
print(new[-3])

## Accessing 2-dimensional arrays

In [ ]:
list_new = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(list_new[0])
print(list_new[0][0])
print('----------------------')
print(list_new[0,2])
print(list_new[1])
# Accessing the first row
print('this is first row',list_new[0,:])
# Accessing the second row
print('this is second row',list_new[1, :])

print("---------------------------------------------------------------------------------")
print("# Alternative 1")
print(list_new[0,])
print('# Alternative 2')
print(list_new[0][:])
print('# Accessing the last 2 elements of the first row')
print(list_new[0,1:])
# list_new[row, col_start:col_end] is NumPy slicing to select specific parts of an array.
print(list_new[0:,0:2])

### Accessing 3-dimensional arrays (depth, rows, columns)

In [ ]:
three = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
])
print(three.shape)
print()
print(three[0])
print()
print(three[1])
print('')
print(three[1][1])
print('(depth, rows, columns)')
print('depth pass the which block , rows,columns')
print(three[1][1][2])
print()
print(three[1][0:][0:])
print()
print(three[1,0:,0:])

#### Accessing elements based on conditions



In [56]:
liss = np.array([
    [1,2,3,4],[5,6,7,8]
])
cond = liss >=5
print(cond)

[[False False False False]
 [ True  True  True  True]]


#### if we just want the number which are evven or odd

In [58]:
dig = np.array([
    [1,2,4,5,6,7,8,9],[10,11,12,13,14,15,16,18]
])
even =dig [dig%2 == 0]
print(even)
odd = dig[dig%2==1]
print(odd)

[ 2  4  6  8 10 12 14 16 18]
[ 1  5  7  9 11 13 15]


## Array Manipulations

### adding the element 

In [ ]:
array = np.array([1,2,3])
array = np.append(array,4)
print(array)

In [60]:
array2 = np.array([1,2,3])
array2 = np.append(array2,[4,5,6,7])
print(array2)

[1 2 3 4 5 6 7]


### deleted the element 

In [ ]:
array3 = np.array([1,2,3,4,5,6,7,8,9])
array3 = np.delete(array3,obj = 2) # delete the index number in obj
print(array3)

In [ ]:
array4 = np.array([1,2,3,4,5,6,7,8,9])
array4 = np.delete(array4,obj = [0,2])# deleted the index number of 0,2
print(array4)

### Replacing elements 

In [ ]:
array5 = np.array([1,2,3,4,5,6,7,8,9])
array5[2]=5
print(array5)

In [ ]:
array6 = np.array([1,2,3,4,5,6,7,8,9])
array6[0:2]=[-1,-2]
print(array6)

In [ ]:
array7= np.array([1,2,3,4,5,6,7,8,9])
array7[-5:]=[100,200,300,400,500]
print(array7)

### Adding elements to 2-dimensional arrays

In [74]:
arr = np.array([
    [1,2,3,4],[-1,-2,-3,-4]
])
print(np.append(arr,0))

[ 1  2  3  4 -1 -2 -3 -4  0]


 This is because np.append() treats the array as a flattened 1-dimensional array when appending elements.

 We will learn how to use the reshape() method in later sections.

### Deleting elements from 2-dimensional arrays

In [80]:
arr = np.array([
    [1,2,3,4],[-1,-2,-3,-4]
])
print('deleted array:',np.delete(arr,0)) #pass the index number 

deleted array: [ 2  3  4 -1 -2 -3 -4]


same reason why we goted  same one daimensional array

In [106]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print('deleted array',np.delete(arr2,0,axis=1)) # for delete the column 
print('deleted array',np.delete(arr2,0,axis=0)) #for delete the first rows

deleted array [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
deleted array [[ 5  6  7  8]
 [ 9 10 11 12]]


0 → The index of the row to delete (first row).

axis=0 → Deletes entire row (row-wise deletion).

In [110]:
print(np.delete(arr2,[0,1],1))  # arr2,[starting index number ,end ]

[[ 3  4]
 [ 7  8]
 [11 12]]


[0, 1] → The indices of the columns to remove.

axis=1 → Specifies that the operation should be column-wise (not row-wise).



In [118]:
print(np.delete(arr2,[1,3],axis=1))

[[ 1  3]
 [ 5  7]
 [ 9 11]]


### Replacing elements in 2-dimensional arrays

In [123]:
arr4 = np.array([
    [4,5,6],[7,8,9]
])

In [125]:
arr4[0]=[1,2,3]
print(arr4)

[[1 2 3]
 [7 8 9]]


#### replacing column wise

In [134]:
arr5 = np.array([
    [1,2,3,],[4,5,6],[7,8,9]
])
arr5[:,0]=[0,0,0]
arr5[:,2]=[0,0,0]
print(arr5)

[[0 2 0]
 [0 5 0]
 [0 8 0]]


In [156]:
arrr = np.array([
    [1,2],[3,4],[5,6],[7,8]
])
new_arr  = np.append(arrr,[[10,10],[11,11],[12,12],[13,13]],axis=0) # append always add at the end of the element
new_arr2 = np.append(arrr,[[10,10],[11,11],[12,12],[13,13]],axis=1)
print(new_arr)
print('for columns')
print(new_arr2)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [10 10]
 [11 11]
 [12 12]
 [13 13]]
for columns
[[ 1  2 10 10]
 [ 3  4 11 11]
 [ 5  6 12 12]
 [ 7  8 13 13]]


# Arithmetic Operations

## Performing vector addition with arrays

In [163]:
v1 = np.array([1,2,3,4])
v2 = np.array([1,2,3,4])
res = v1+v2
print(res)

[2 4 6 8]


In [167]:
v3 = np.array( [40,50,60])
v4 = np.array([10,10,10])
res2 = v3-v4
print(res2)

[30 40 50]


In [169]:
v1 = np.array([1,2,3,4])
fin = v1+10
print(fin)

[11 12 13 14]


Similar principle is followed when performing addition and subtraction operations on 2-dimensional arrays as well. Consider the following.



In [180]:
arr2 = np.array([
    [10,20],[30,40]
])
arr3 = np.array([
    [10,10],[10,10]
])S
add = arr2+arr3
print(add)
print('now performing subtract')
sub = arr2-arr3
print(sub)

[[20 30]
 [40 50]]
now performing subtract
[[ 0 10]
 [20 30]]


In [182]:
nw = np.array([
    [10,20],[40,50]
])
sumar = nw+5
print(sumar)

[[15 25]
 [45 55]]


We can also perform the scalar addition on a specific row by accessing that specific row and adding the scalar as shown below.

In [249]:
var = np.array([
    [1,2,3],[4,5,6]
])
row=var[0:1]=var[0:1]+10 #it is a row wise addition
var


array([[11, 12, 13],
       [ 4,  5,  6]])

In [259]:
var1 = np.array([
    [1,2,3],[4,5,6]
])
var1[:,1:]=var[:,1:] +10 # it is column wise
var1

array([[ 1, 22, 23],
       [ 4, 15, 16]])

In [273]:
var = np.array([
    [
        [1,2,3],[4,5,6],[7,8,9]
    ],[
        [10,10,10],[20,20,20],[30,30,30]
    ]
])
var2 = np.array([
    [
        [10,20,30],[40,50,60],[70,80,90]
    ],[
        [1,1,1],[2,2,2],[3,3,3]
    ]
])
addi = var + var2
print(addi)
print("-------------------------------------------------------------------------------------------------")
sub= var-var2
print(sub)

[[[11 22 33]
  [44 55 66]
  [77 88 99]]

 [[11 11 11]
  [22 22 22]
  [33 33 33]]]
-------------------------------------------------------------------------------------------------
[[[ -9 -18 -27]
  [-36 -45 -54]
  [-63 -72 -81]]

 [[  9   9   9]
  [ 18  18  18]
  [ 27  27  27]]]


In [279]:
np_arr = np.array([[[14, 16, 18],
                    [20, 22, 24]],
                   
                   [[26, 28, 30],
                    [32, 34, 36]]])
new = np_arr[1:,:,0]+10
new

array([[36, 42]])

### Performing multiplication and division with arrays

In [288]:
varm = np.array([
    [
        [1,2,3],[4,5,6],[7,8,9]
    ],
    [
        [10,11,12],[13,14,15],[16,17,18]
    ]
])
fin = varm*100000000000
fin

array([[[ 100000000000,  200000000000,  300000000000],
        [ 400000000000,  500000000000,  600000000000],
        [ 700000000000,  800000000000,  900000000000]],

       [[1000000000000, 1100000000000, 1200000000000],
        [1300000000000, 1400000000000, 1500000000000],
        [1600000000000, 1700000000000, 1800000000000]]])

In [296]:
 mul=varm[1,1,:] =varm[1,1,:]*10
mul
varm

array([[[     1,      2,      3],
        [     4,      5,      6],
        [     7,      8,      9]],

       [[    10,     11,     12],
        [130000, 140000, 150000],
        [    16,     17,     18]]])

division

In [300]:
varm = varm/2
varm

array([[[5.0e-01, 1.0e+00, 1.5e+00],
        [2.0e+00, 2.5e+00, 3.0e+00],
        [3.5e+00, 4.0e+00, 4.5e+00]],

       [[5.0e+00, 5.5e+00, 6.0e+00],
        [6.5e+04, 7.0e+04, 7.5e+04],
        [8.0e+00, 8.5e+00, 9.0e+00]]])

In [303]:
arr_1 = np.array([[2, 4], [-3, -2], [1, 1]])
arr_2 = np.array([[-9, -1], [5,6], [3,4]])
arr_1 * arr_2 

array([[-18,  -4],
       [-15, -12],
       [  3,   4]])

In [305]:
new_arr=np.array([[1,2],[3,4]])
new_arr=new_arr**2
new_arr

array([[ 1,  4],
       [ 9, 16]])

## Dimensional Operations

In [5]:
array_1d  = np.array([1,2,3,4,5,6,7,8,9])
sum_arr = array_1d.sum()
print('the od of 1d array',sum_arr)

the od of 1d array 45


In [7]:
mean_arr = array_1d.mean()
print('the mean of array',mean_arr)

the mean of array 5.0


Note: In a 1D array, specifying the axis does not change the result because there's only one axis (axis 0).



#### Let us move on to the sum operation for 2D arrays.

In [27]:
array_2d = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
sum_arr = array_2d.sum()
print('the sum of 2d array',sum_arr)
array_2d.sum(axis = 0) # sum with column

the sum of 2d array 36


array([ 6,  8, 10, 12])

In [25]:
array_2d.sum(axis = 1) # sumwith rows

array([10, 26])

In [29]:
array_2d.prod()

np.int64(40320)

In [31]:
array_2d.prod(axis = 0) #[1*5,2*6,3*7,4*8]

array([ 5, 12, 21, 32])

In [33]:
array_2d.prod(axis = 1) #[1*2*3*4]

array([  24, 1680])

In [35]:
array_2d.mean()

np.float64(4.5)

In [37]:
array_2d.mean(axis = 0) #mean column wise 

array([3., 4., 5., 6.])

In [39]:
array_2d.mean(axis = 1) # mean row wise

array([2.5, 6.5])

In [41]:
array_3d = np.array([[[1, 2],
                      [3, 4]],

                     [[5, 6],
                      [7, 8]],

                     [[9, 10],
                      [11, 12]]])


In [43]:
array_3d.sum()

np.int64(78)

In [45]:
array_3d.sum(axis = 0) #New array = [[ (1+5+9),   (2+6+10) ],  
                                   # [ (3+7+11),  (4+8+12) ]]    this how its is work 


array([[15, 18],
       [21, 24]])

In [51]:
array_3d.sum(axis = 1)   #First layer:    [[1, 2], [3, 4]]  
                    # Sum along rows:  [ (1+3), (2+4) ]  → [4, 6]

                    #Second layer:   [[5, 6], [7, 8]]  
                   # Sum along rows:  [ (5+7), (6+8) ]  → [12, 14]

                   # Third layer:    [[9, 10],[11, 12]] 
                   # Sum along rows:  [ (9+11), (10+12) ]  → [20, 22]


array([[ 4,  6],
       [12, 14],
       [20, 22]])

In [59]:
sum_axis_2 = array_3d.sum(axis=2)
print(sum_axis_2)

[[ 3  7]
 [11 15]
 [19 23]]


First layer:    [[1, 2],  
                 [3, 4]]  
Sum along cols:  [ (1+2), (3+4) ]  → [3, 7]

Second layer:   [[5, 6],  
                 [7, 8]]  
Sum along cols:  [ (5+6), (7+8) ]  → [11, 15]

Third layer:    [[9, 10],  
                 [11, 12]]  
Sum along cols:  [ (9+10), (11+12) ]  → [19, 23]
