# Numpy

In [2]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

### creating the empty array

In [9]:
np_array = np.array([])

In [11]:
np_array

array([], dtype=float64)

### creating array from list 

In [18]:
list1 = [1,2,3,4,5,6,7,8,9]
cvt_array = np.array(list1)
print(cvt_array,type(cvt_array))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


### creating array from tuples

In [25]:
tuple1 = (1,2,3,4,5,6,7,8,9,10)
tuple_to_array = np.array(tuple1)
print(tuple_to_array,type(tuple_to_array))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


## [1,2,3,4,5,6,7,8,9] this are one dimentional array 

### datatype

In [30]:
float1 = np.array([1.0,2.5,3.6,4.5,1.8,5.2])
data_type = float1.dtype
print(data_type)

float64


## string array 

In [36]:
str_array = np.array(['apple','banana','mango','orange','kiwi'])
print(str_array,str_array.dtype)

['apple' 'banana' 'mango' 'orange' 'kiwi'] <U6


## uppercasting

In [69]:
str_upper = np.array(['apple',100,2.565,True])
print(type(str_upper) ,str_upper) # here all data convert to the string beacause string are more flexiable 

<class 'numpy.ndarray'> ['apple' '100' '2.565' 'True']


Notice that in the code given above, numerical values have been converted into strings. This is because arrays can't have mixed types of data. Therefore, NumPy performs what is called upcasting, which is automatic promotion of data types to a higher-level type to ensure that all elements in an operation can be handled consistently. NumPy will upcast the data types to a common type that can accommodate both inputs without loss of information.



### array from set

In [53]:
set1 = {1.2,2.3,5.6,4.987,1.254,1.478}
array1 = np.array(set1)
print(array1,type(array1))

{1.2, 2.3, 1.254, 4.987, 5.6, 1.478} <class 'numpy.ndarray'>


In [55]:
print(array1[0])

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

Notice even though we have created an array from a set, the resulting array retains the curly braces from the set. Further, when we tried to access an element from the resulting array, the interpreter threw the above error.


This is mainly because sets in Python are unordered collections of unique elements, whereas NumPy arrays are ordered collections. NumPy creates a zero-dimensional array which cannot be indexed. Hence creating arrays directly from sets is not a common practice, and it's not typically suggested.





## Understanding NumPy Arrays and Mixed Data Types


NumPy is designed to work with large amounts of numerical data efficiently. One of its key features is that all elements in a NumPy array must have the same data type (e.g., all integers, all floats, or all strings).

But what happens when we try to create a NumPy array from a list containing different data types?

In [60]:
mixedlist = [[1,2,3],'apple',10.245,-5,True]
ct_array = np.array(mixedlist)
print(ct_array)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

🔴 This gives an error because NumPy expects a consistent data type, but our list contains:

A list [2, 3, 1]
A string 'New York'
A float 5.6
An integer -10
Another string 'John'
These data types are too different for NumPy to convert into a single, uniform array.



so the solution is 

In [66]:
ct_array = np.array(object = mixedlist, dtype ='object')
print(ct_array, type(ct_array))

[list([1, 2, 3]) 'apple' 10.245 -5 True] <class 'numpy.ndarray'>


To force NumPy to accept different types, we can specify dtype='object'. This tells NumPy to treat every element as a general Python object:

# Multidimensional Arrays

## creating 2d array 

In [5]:
list_2_dim = [1,2,3],[4,5,6]
array_2d  = np.array(list_2_dim)
print(array_2d)

[[1 2 3]
 [4 5 6]]


## creating 3d array 

In [10]:
list_3d =[ [[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]]
array_3d = np.array(list_3d)
print(array_3d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Checking the number of dimensions in an array

In [29]:
tem = [
    [
        [20,24,25,26,29,24],
        [24,22,21,27,26,28],
        [22,25,24,25,26,27]
    ],
    [
        [25,26,23,24,24,25],
        [24,25,26,27,28,29],
        [29,21,20,24,26,23]
    ]
]
mk_array = np.array(tem)
mk_dim = np.ndim(mk_array)
print('the dimensional of this array is ',mk_dim)

the dimensional of this array is  3


### shape

In [33]:
# 1D array (Vector)
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)
print("Shape:", array_1d.shape)

# 2D array (Matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(array_2d)
print("Shape:", array_2d.shape)

# 3D array (Tensor)
array_3d = np.array([
    [
        [1, 2, 3], [4, 5, 6]
    ],
    [
        [7, 8, 9], [10, 11, 12]
    ]
])
print("\n3D Array:")
print(array_3d)
print("Shape:", array_3d.shape)

1D Array:
[1 2 3 4 5]
Shape: (5,)

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)


simple way to make the array according to there dimensional

In [43]:
var = np.array([1,2,3],ndmin = 4)
dimen_array = np.ndim(var)
print(var)
print(var.shape)
print(dimen_array)

[[[[1 2 3]]]]
(1, 1, 1, 3)
4


### key difference of ndim and ndmin

Use ndim to check how many dimensions an array has.


Use ndmin to force an array to have at least a certain number of dimensions.

In [5]:
var = np.array([[2, 5, 3, 4], [1, 6, 4, 2], [7, 8, 4, 1]]) 
var_dim = np.ndim(var)
print(var)
print(var_dim)
print('the size func :',var.size)
print('the shape func :',var.shape)
print(var.shape[0])
print(var.shape[1])

[[2 5 3 4]
 [1 6 4 2]
 [7 8 4 1]]
2
the size func : 12
the shape func : (3, 4)
3
4


# Accessing NumPy Array Elements

### Accessing elements in 1-dimensional arrays

In [87]:
new = np.array([1,2,3,4,5,6,7,8,9])
print(new[0:5])
print(new[0:9:2])#act same like the slicing 
print(new[::-1])
print(new[5:0:-1])
print(new[-1])
print(new[-3])

[1 2 3 4 5]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1]
[6 5 4 3 2]
9
7


## Accessing 2-dimensional arrays

In [33]:
list_new = np.array([
    [1,2,3,4],
    [5,6,7,8]
])
print(list_new[0])
print(list_new[0][0])
print('----------------------')
print(list_new[0,2])
print(list_new[1])
# Accessing the first row
print('this is first row',list_new[0,:])
# Accessing the second row
print('this is second row',list_new[1, :])

print("---------------------------------------------------------------------------------")
print("# Alternative 1")
print(list_new[0,])
print('# Alternative 2')
print(list_new[0][:])
print('# Accessing the last 2 elements of the first row')
print(list_new[0,1:])
# list_new[row, col_start:col_end] is NumPy slicing to select specific parts of an array.
print(list_new[0:,0:2])

[1 2 3 4]
1
----------------------
3
[5 6 7 8]
this is first row [1 2 3 4]
this is second row [5 6 7 8]
---------------------------------------------------------------------------------
# Alternative 1
[1 2 3 4]
# Alternative 2
[1 2 3 4]
# Accessing the last 2 elements of the first row
[2 3 4]
[[1 2]
 [5 6]]


### Accessing 3-dimensional arrays (depth, rows, columns)

In [64]:
three = np.array([
    [
        [1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]
    ],
    [
        [13,14,15,16],
        [17,18,19,20],
        [21,22,23,24]
    ]
])
print(three.shape)
print()
print(three[0])
print()
print(three[1])
print('')
print(three[1][1])
print('(depth, rows, columns)')
print('depth pass the which block , rows,columns')
print(three[1][1][2])
print()
print(three[1][0:][0:])
print()
print(three[1,0:,0:])

(2, 3, 4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[17 18 19 20]
(depth, rows, columns)
depth pass the which block , rows,columns
19

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


#### Accessing elements based on conditions



In [69]:
liss = np.array([
    [1,2,3,4],[5,6,7,8]
])
cond = liss >=5
print(cond)

[[False False False False]
 [ True  True  True  True]]


#### if we just want the number which are evven or odd

In [84]:
dig = np.array([
    [1,2,4,5,6,7,8,9],[10,11,12,13,14,15,16,18]
])
even =dig [dig%2 == 0]
print(even)
odd = dig[dig%2==1]
print(odd)

[ 2  4  6  8 10 12 14 16 18]
[ 1  5  7  9 11 13 15]


## Array Manipulations

### adding the element 

In [10]:
array = np.array([1,2,3])
array = np.append(array,4)
print(array)

[1 2 3 4]


In [34]:
array2 = np.array([1,2,3])
array2 = np.append(array2,[4,5,6,7])
print(array2)

[1 2 3 4 5 6 7]


### deleted the element 

In [40]:
array3 = np.array([1,2,3,4,5,6,7,8,9])
array3 = np.delete(array3,obj = 2) # delete the index number in obj
print(array3)

[1 2 4 5 6 7 8 9]


In [44]:
array4 = np.array([1,2,3,4,5,6,7,8,9])
array4 = np.delete(array4,obj = [0,2])# deleted the index number of 0,2
print(array4)

[2 4 5 6 7 8 9]


### Replacing elements 

In [49]:
array5 = np.array([1,2,3,4,5,6,7,8,9])
array5[2]=5
print(array5)

[1 2 5 4 5 6 7 8 9]


In [51]:
array6 = np.array([1,2,3,4,5,6,7,8,9])
array6[0:2]=[-1,-2]
print(array6)

[-1 -2  3  4  5  6  7  8  9]


In [65]:
array7= np.array([1,2,3,4,5,6,7,8,9])
array7[-5:]=[100,200,300,400,500]
print(array7)

[  1   2   3   4 100 200 300 400 500]


### Adding elements to 2-dimensional arrays

In [70]:
arr = np.array([
    [1,2,3,4],[-1,-2,-3,-4]
])
print(np.append(arr,0))

[ 1  2  3  4 -1 -2 -3 -4  0]


 This is because np.append() treats the array as a flattened 1-dimensional array when appending elements.

 We will learn how to use the reshape() method in later sections.

### Deleting elements from 2-dimensional arrays

In [77]:
arr = np.array([
    [1,2,3,4],[-1,-2,-3,-4]
])
print('deleted array:',np.delete(arr,0))

deleted array: [ 2  3  4 -1 -2 -3 -4]


same reason why we goted  same one daimensional array

In [86]:
arr2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print('deleted array',np.delete(arr2,0,axis=0))

deleted array [[ 5  6  7  8]
 [ 9 10 11 12]]
